アプリ側での以下の実行エラー解消のため
Launching lib/main.dart on Pixel 4a in debug mode...
/Users/mai/StudioProjects/flutter/android/gradlew: line 59: cd: "/Users/mai/StudioProjects/flutter/android/: No such file or directory
Incorrect package="net.touchcapture.qr.flutterqr" found in source AndroidManifest.xml: /Users/mai/.pub-cache/git/qr_code_scanner-c15468c055d89ef3de22480f71c0c828688459f9/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
Recommendation: remove package="net.touchcapture.qr.flutterqr" from the source AndroidManifest.xml: /Users/mai/.pub-cache/git/qr_code_scanner-c15468c055d89ef3de22480f71c0c828688459f9/android/src/main/AndroidManifest.xml.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qr_code_scanner:processDebugManifest'.
> A failure occurred while executing com.android.build.gradle.tasks.ProcessLibraryManifest$ProcessLibWorkAction
   > Incorrect package="net.touchcapture.qr.flutterqr" found in source AndroidManifest.xml: /Users/mai/.pub-cache/git/qr_code_scanner-c15468c055d89ef3de22480f71c0c828688459f9/android/src/main/AndroidManifest.xml.
     Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
     Recommendation: remove package="net.touchcapture.qr.flutterqr" from the source AndroidManifest.xml: /Users/mai/.pub-cache/git/qr_code_scanner-c15468c055d89ef3de22480f71c0c828688459f9/android/src/main/AndroidManifest.xml.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 17s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).